### ISSUE TITLE
Pre-trained model available?

### ISSUE THREAD

**Issue by ndrplz** [nywang16/Pixel2Mesh#1]
Hi @nywang16 ,

first greetings for this impressive work. 

I'm wondering if the pre-trained model will be available for download. In the README you're mentioning a demo, but I don't understand if it's the same thing.
Thank you!

**Comment by nywang16** [comment]
Thanks for your Interests, we are still working hard on testing the code, and it will be released in two days.

**Comment by CesarWu410** [comment]
Hi @nywang16 ,
when I ran this project, I got a error call "tensorflow.python.framework.errors_impl.NotFoundError: ./cd_dist.so: undefined symbol: _ZTIN10tensorflow8OpKernelE".
Could u tell me how to build "cd_dist.so" correctly
Thank you!

**Comment by nywang16** [comment]
@CesarWu410 One solution is swiching your tensorflow to version 1.3 if you want to used it directly.
Another solution is to build it yourself, please refer to https://github.com/fanhqme/PointSetGeneration

**Comment by al093** [comment]
Hi @nywang16,
I did try to build TensorFlow 1.3 with Bazel 0.5.4 on Ubuntu 16.04. But still when loading the library "cd_dist.so" It complains :

tensorflow.python.framework.errors_impl.NotFoundError: ./cd_dist.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

I think it may because of incompatible GCC versions. Probably cd_dist.so was built by GCC4.xx and I think Bazel is using GCC5.4 on my platform. But this is just a wild guess, i have no idea how Bazel is compiling TensorFlow.

Do you have any solution for this ?

--
Alok

**Comment by walsvid** [comment]
Hi @al093, you can first complete the compilation of TensorFlow and continue to use Bazel or any tool. Then recompile `cd_dist.so` using the compatible version GCC according to this issue #2.

**Comment by ndrplz** [comment]
@nywang16 Thanks!

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
