### ISSUE TITLE
How wo get the groundtruth point cloud with normal vector from ShapeNet dataset?

### ISSUE THREAD

**Issue by tangjilin** [nywang16/Pixel2Mesh#27]
Given the 3D model in the shapenet dataset(.obj files), how can I get the groundtruth point cloud with normal vector in your way to train my own model?
 Besides, You said that you transformed it to corresponding coordinates in camera coordinate based on camera parameters from the Rendering Dataset.  I don't understand it clearly.  Can you share me how to preprocess the groundtruth point to prepare my data to train your model? I am not familiar with it indeed. Thanks very much!

**Comment by nywang16** [comment]
@tangjilin see data_generation folder

**Comment by tangjilin** [comment]
@nywang16 Thanks very much！

**Comment by KnightOfTheMoonlight** [comment]
Hi, @nywang16 After checking the https://github.com/nywang16/Pixel2Mesh/blob/master/GenerateData/4_make_auxiliary_dat_file.ipynb. I have the following confusions about the data generation part.

About the original data from shapenetcore.v1, are they all resized to be put in a unit cube, which are of size (-0.5,0.5)^3? And why would you choose ellipsoid with a size of (0.2,0.2,0.4) radius?

And you use your rendering_metacamera.txt annotations to transform 3d object to camera coordinates?

**Comment by walsvid** [comment]
Hi @KnightOfTheMoonlight , our method is not sensitive to initial shape, you can also use sphere. The reason for using the ellipsoid as the initial may be that the average shape of the object is closer to the ellipsoid.

**Comment by EdwardSmith1884** [comment]
It is kind of sensitive though right? You want the initial mesh's vertices to project "nicely" over the input image so that the sampled image features  which are placed on those vertices properly capture the information in the image. If the range of vertices when projected into images space is too small in either direction information about the object will be lost, and similarly if the range is too large.  I would think any shape with uniformly distributed vertices in the range of (-0.5,0.5)^3 would be fine.

**Comment by walsvid** [comment]
Hi, @EdwardSmith1884 . I don't think the initial shape is very sensitive. According to the performance of graph convolution during training, no matter what the initial shape is, it seems that graph convolution tends to learn the shape completely from scratch. The shape of the three-dimensional mesh output by the first few epochs is basically irrelevant, but is mainly affected by topology. Specifically, our experiments in the ECCV supp are as follows. 
<img width="734" alt="截屏2020-02-2523 22 54" src="https://user-images.githubusercontent.com/17134911/75261727-75686980-5826-11ea-8aa2-bad2acb8269b.png">
<img width="747" alt="截屏2020-02-2523 23 05" src="https://user-images.githubusercontent.com/17134911/75261746-7c8f7780-5826-11ea-8f2b-93039235bb81.png">

**Comment by EdwardSmith1884** [comment]
I think these all do well because they basically have uniformly distributed vertices in the range of (-0.5,0.5)^3 . I would think if the ellipsoid was very thin in one dimension, or the sphere was 1/10 the scale it would do worse. I guess I mean shape doesn't really matter but scale does, at least I observed worse much worse accuracy when I didn't scale the initial mesh properly.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
