### ISSUE TITLE
Not getting good results, possibly a png settings issue?

### ISSUE THREAD

**Issue by 10Exahertz** [nywang16/Pixel2Mesh#94]
I tested out the demo.py on the original car.png provided

Input:
![car](https://user-images.githubusercontent.com/34243218/101098458-f2ccc180-3590-11eb-899d-8942c5f9c12f.png)

Output:
![image](https://user-images.githubusercontent.com/34243218/101098525-10019000-3591-11eb-917b-ba2962e35952.png)

This looks good, as expected.
Then I took a screenshot of the input photo and tried again.

Input2: 
![carar](https://user-images.githubusercontent.com/34243218/101098580-2a3b6e00-3591-11eb-98e9-7b3856b1b9a1.png)

Output2: 
![image](https://user-images.githubusercontent.com/34243218/101098637-3e7f6b00-3591-11eb-8aed-aa28c5866c1c.png)

For some reason after taking a screenshot of it and saving it in paint.net, it thinks the car is a couch-like object

I am very confused, any help would be greatly appreciated.

I am running it with Tensorflow 1.15.0, on Python 3.6 and Cuda 9.0
But I dont see how the demo works fine on the original images but not on other png's. Is there a certain png setting.

**Comment by topinfrassi01** [comment]
Hey, so I know this is an old issue, and I'm not one of the maintainers of this project, but I think I know what problem you're facing.

I downloaded the two images you're using and let's look at them side by side :

![image](https://user-images.githubusercontent.com/5103255/120653305-90c11c00-c44e-11eb-8447-8b645279c112.png)
![image](https://user-images.githubusercontent.com/5103255/120653403-a2a2bf00-c44e-11eb-8339-29a49ae5b7a0.png)

You'll notice the car isn't at the same position in both images, however Pixel2Mesh uses the object's pose parameters to project model's vertices to the image in order to get the features necessary for deformation.

So, the problem is that when you took a screenshot, the position of the model in the image moved and that translation wasn't applied to the pose parameters that are necessary for deformation, which means the mesh's vertices are projected at the same 2D coordinates as before and they don't "land" where they should, hence the bad deformation.

To fix your problem, you would need to re-estimate the position of the model in the image and fix the pose parameters in consequence.

**Comment by 10Exahertz** [comment]
Actually I just figured it out.
The png settings were left in sRGB when I saved them.
When I disabled that setting on Photoshop the images work.

Performance leaves a lot to be desired, and it overfits to Furniture often, but if the real life data I was inputting into the model sometimes led to very good results.
